### ISSUE TITLE
Check_All() function fails

### ISSUE THREAD

**Issue by panagioto** [its-a-feature/HealthInspector#1]
While other functions are working fine (User_Global_Preferences()/Spaces_Check()), Check_All() function fails to run. I tried to append it at the end of the HealthInspector.js file and run it locally:

**osascript -l JavaScript HealthInspector.js**

**HealthInspector.js:435:519: execution error: Error on line 12: TypeError: undefined is not an object (evaluating 'attributes['NSFileOwnerAccountID']') (-2700)**

I tried it on **Mojave 10.14.6**.

**Comment by its-a-feature** [comment]
Hm, I think it's something not unique to 10.14.6, but maybe unique to your system. 

That specific attribute is called in a function related to LaunchAgents and LaunchDaemons. Essentially, when going through LaunchAgents and LaunchDaemons, I look at the corresponding program that gets executed and check the file permissions on _that_ file in case there are ways you can abuse that for persistence or privilege escalation (similar to abusing weak file permissions for services in Windows). My guess is there's something abnormal about one of those files (like maybe the corresponding program is no longer there). 

I'll add in a check for this sort of thing, but I'd still be really curious about those files on the system you're testing. I'd love to see the `Program Attributes` sections of those plists if possible, or at least let me know if any of them deviate from normal in some way.

**Comment by panagioto** [comment]
Sorry @its-a-feature , I forgot to close that. I had a typo actually that is why I had the above error.
